### ISSUE TITLE
Suggestion for fit_sys object: Have a 'notes' field

### ISSUE THREAD

**Issue by seaveredge** [GerbenBeintema/deepSI#6]
Just an idea: 

In some cases, where you train and save models for multiple scenarios, it is nice to know what scenario was associated with the saved file. This can be done with an elaborate file name, but it can also be nice if the saved object has a 'notes' field, where the user can put a summary of the specific scenario, which avoids plunging through the variables to see which cases was used...

**Comment by GerbenBeintema** [comment]
As for the suggestion, luckily enough this is already supported by coincidence since the saving in deepSI saves the entire object using the pickle module. e.g.

![image](https://user-images.githubusercontent.com/44409127/177873785-4d4a9e3b-352e-4be0-9df3-7d4c6a451301.png)

I see this idea expanding into two directions which would make the documentation automatic.

* Somehow saving the "main" file as a string together with the system when saving any system. However, this raises some difficult questions about what is considered the "main" file (e.g. notebooks and interfaces).
* The other possibility is to create a log file of the computations which would save all relevant operations performed on the system or model. However, I'm not entirely sure I would even start to implement this.
